name: Update rooms.json
on:
  push:
    paths-ignore:
      - 'rooms.json'
  schedule:
    - cron: '55 4 * * 0-5'    # Weekdays @ EOD (11:55 PM PST) + Sundays for weekend drops/adds
  workflow_dispatch:

jobs:
  course-updater:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v3
    - run: dir
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
        cache-dependency-path: modules.txt
    - run: pip install -r modules.txt

    - name: Run convert.py
      run: |
        python convert.py
        rm courses.json && dir

    - name: Push updates
      run: |
        git add -A
        git config user.name "Vacansee"
        git config user.email "rpi.vacansee@gmail.com"
        git commit -m "Updated on $(TZ=EST5EDT date)"
        git push origin main
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
